"""add repositories, runs, jobs, and task queue

Revision ID: 012089361fbb
Revises: a8478c9539ea
Create Date: 2026-07-29 20:43:52.810628

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "012089361fbb"
down_revision: str | Sequence[str] | None = "a8478c9539ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_tasks",
        sa.Column(
            "task_type",
            sa.Enum(
                "backfill_repo",
                "poll_repo",
                "ingest_run",
                "diagnose_run",
                "gc_repo",
                name="task_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "leased", "done", "failed", "dead", name="task_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "next_run_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_tasks")),
    )
    op.create_index(
        "ix_ingestion_tasks_claimable",
        "ingestion_tasks",
        ["priority", "next_run_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index(op.f("ix_ingestion_tasks_status"), "ingestion_tasks", ["status"], unique=False)
    op.create_table(
        "repositories",
        sa.Column("github_id", sa.BigInteger(), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
        sa.UniqueConstraint("owner", "name", name="uq_repositories_owner_name"),
    )
    op.create_index(op.f("ix_repositories_github_id"), "repositories", ["github_id"], unique=True)
    op.create_index(op.f("ix_repositories_name"), "repositories", ["name"], unique=False)
    op.create_index(op.f("ix_repositories_owner"), "repositories", ["owner"], unique=False)
    op.create_table(
        "workflow_runs",
        sa.Column("repository_id", sa.UUID(), nullable=False),
        sa.Column("github_run_id", sa.BigInteger(), nullable=False),
        sa.Column("run_attempt", sa.Integer(), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("head_sha", sa.String(length=40), nullable=False),
        sa.Column(
            "conclusion",
            sa.Enum(
                "success",
                "failure",
                "cancelled",
                "skipped",
                "timed_out",
                "other",
                name="run_conclusion",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_workflow_runs_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_runs")),
        sa.UniqueConstraint(
            "repository_id",
            "github_run_id",
            "run_attempt",
            name="uq_workflow_runs_repo_run_attempt",
        ),
    )
    op.create_index(
        op.f("ix_workflow_runs_conclusion"), "workflow_runs", ["conclusion"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_runs_github_run_id"), "workflow_runs", ["github_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_runs_repository_id"), "workflow_runs", ["repository_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("workflow_run_id", sa.UUID(), nullable=False),
        sa.Column("github_job_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("step_name", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("queued", "in_progress", "completed", name="job_status", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "conclusion",
            sa.Enum(
                "success",
                "failure",
                "cancelled",
                "skipped",
                "timed_out",
                "other",
                name="job_conclusion",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["workflow_runs.id"],
            name=op.f("fk_jobs_workflow_run_id_workflow_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(op.f("ix_jobs_github_job_id"), "jobs", ["github_job_id"], unique=False)
    op.create_index(op.f("ix_jobs_workflow_run_id"), "jobs", ["workflow_run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_workflow_run_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_github_job_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_workflow_runs_repository_id"), table_name="workflow_runs")
    op.drop_index(op.f("ix_workflow_runs_github_run_id"), table_name="workflow_runs")
    op.drop_index(op.f("ix_workflow_runs_conclusion"), table_name="workflow_runs")
    op.drop_table("workflow_runs")
    op.drop_index(op.f("ix_repositories_owner"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_name"), table_name="repositories")
    op.drop_index(op.f("ix_repositories_github_id"), table_name="repositories")
    op.drop_table("repositories")
    op.drop_index(op.f("ix_ingestion_tasks_status"), table_name="ingestion_tasks")
    op.drop_index(
        "ix_ingestion_tasks_claimable",
        table_name="ingestion_tasks",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("ingestion_tasks")
    # ### end Alembic commands ###
