"""add job steps and log line count

Revision ID: 75e44d534e5a
Revises: 8e7f6d4cff06
Create Date: 2026-08-03 18:44:31.844569

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75e44d534e5a"
down_revision: str | Sequence[str] | None = "8e7f6d4cff06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.add_column("jobs", sa.Column("log_line_count", sa.Integer(), nullable=True))
    op.execute("UPDATE jobs SET log_line_count = 0 WHERE log_line_count IS NULL")
    op.alter_column("jobs", "log_line_count", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "log_line_count")
    op.drop_column("jobs", "steps")
    # ### end Alembic commands ###
