"""add workflow run ingestion fields

Revision ID: 8e7f6d4cff06
Revises: cae20c8073cd
Create Date: 2026-08-02 22:04:17.858990

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from buildlens.db.base import _enum
from buildlens.db.models import IngestState

# revision identifiers, used by Alembic.
revision: str = "8e7f6d4cff06"
down_revision: str | Sequence[str] | None = "cae20c8073cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow_runs", sa.Column("workflow_name", sa.String(length=255), nullable=True))
    op.add_column("workflow_runs", sa.Column("branch", sa.String(length=255), nullable=True))
    op.add_column(
        "workflow_runs",
        sa.Column("ingest_state", _enum(IngestState, "ingest_state"), nullable=True),
    )
    op.execute("UPDATE workflow_runs SET workflow_name = 'unknown' WHERE workflow_name IS NULL")
    op.alter_column("workflow_runs", "workflow_name", nullable=False)
    op.add_column("workflow_runs", sa.Column("raw_log_uri", sa.String(length=500), nullable=True))
    op.execute("UPDATE workflow_runs SET ingest_state = 'pending' WHERE ingest_state IS NULL")
    op.alter_column("workflow_runs", "ingest_state", nullable=False)
    op.alter_column(
        "workflow_runs",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "workflow_runs",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.create_index(
        op.f("ix_workflow_runs_ingest_state"), "workflow_runs", ["ingest_state"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflow_runs_ingest_state"), table_name="workflow_runs")
    op.alter_column(
        "workflow_runs",
        "completed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "workflow_runs",
        "started_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_column("workflow_runs", "raw_log_uri")
    op.drop_column("workflow_runs", "ingest_state")
    op.drop_column("workflow_runs", "branch")
    op.drop_column("workflow_runs", "workflow_name")
    # ### end Alembic commands ###
